name: myapp

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/home.png
    - assets/page-1/images/frame-2109.png
    - assets/page-1/images/wifi.png
    - assets/page-1/images/group-14.png
    - assets/page-1/images/battery.png
    - assets/page-1/images/.png
    - assets/page-1/images/frame-2109-sFP.png
    - assets/page-1/images/ellipse-3.png
    - assets/page-1/images/ellipse-21.png
    - assets/page-1/images/ellipse-19.png
    - assets/page-1/images/battery-LeM.png
    - assets/page-1/images/bg.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/back.png
    - assets/page-1/images/wifi-qCD.png
    - assets/page-1/images/wifi-51K.png
    - assets/page-1/images/-oo7.png
    - assets/page-1/images/-SwB.png
    - assets/page-1/images/sri-lanka-lk.png
    - assets/page-1/images/arrowdropdown.png
    - assets/page-1/images/ellipse-21-bTX.png
    - assets/page-1/images/-oWy.png
    - assets/page-1/images/back-icon.png
    - assets/page-1/images/back-icon-AwB.png
    - assets/page-1/images/back-ZDs.png
    - assets/page-1/images/group-23.png
    - assets/page-1/images/group-23-jE9.png
    - assets/page-1/images/wifi-Lmf.png
    - assets/page-1/images/battery-jDT.png
    - assets/page-1/images/home-mA9.png
    - assets/page-1/images/frame-2109-VkM.png
    - assets/page-1/images/-bEy.png
    - assets/page-1/images/battery-z8R.png
    - assets/page-1/images/recent.png
    - assets/page-1/images/ellipse-19-fwo.png
    - assets/page-1/images/battery-2Su.png
    - assets/page-1/images/battery-mmB.png
    - assets/page-1/images/ellipse-22.png
    - assets/page-1/images/battery-JpH.png
    - assets/page-1/images/wifi-FN9.png
    - assets/page-1/images/battery-NDP.png
    - assets/page-1/images/check.png
    - assets/page-1/images/back-icon-YK3.png
    - assets/page-1/images/-ipR.png
    - assets/page-1/images/frame-2109-4Vw.png
    - assets/page-1/images/ellipse-20.png
    - assets/page-1/images/frame-2109-jCd.png
    - assets/page-1/images/battery-88H.png
    - assets/page-1/images/arrowdropdown-wms.png
    - assets/page-1/images/ellipse-3-8tH.png
    - assets/page-1/images/vector-FDj.png
    - assets/page-1/images/check-7r9.png
    - assets/page-1/images/wifi-cp1.png
    - assets/page-1/images/ellipse-22-AXK.png
    - assets/page-1/images/bg-zg1.png
    - assets/page-1/images/-YNd.png
    - assets/page-1/images/group-33300.png
    - assets/page-1/images/recent-KeR.png
    - assets/page-1/images/group-15.png
    - assets/page-1/images/frame-2109-v2u.png
    - assets/page-1/images/group-22.png
    - assets/page-1/images/default-marker-component.png
    - assets/page-1/images/bg-8Rf.png
    - assets/page-1/images/eyefill-Zvq.png
    - assets/page-1/images/frame-2109-ED7.png
    - assets/page-1/images/ellipse-20-3kM.png
    - assets/page-1/images/eyefill.png
    - assets/page-1/images/back-icon-6QZ.png
    - assets/page-1/images/frame-2109-KwX.png
    - assets/page-1/images/-odj.png
    - assets/page-1/images/-e5P.png
    - assets/page-1/images/back-icon-vjb.png
    - assets/page-1/images/recent-jVK.png
    - assets/page-1/images/frame-2109-5ZB.png
    - assets/page-1/images/wifi-41o.png
    - assets/page-1/images/ellipse-20-81f.png
    - assets/page-1/images/back-mKX.png
    - assets/page-1/images/eyefill-GTB.png
    - assets/page-1/images/-E97.png
    - assets/page-1/images/calendar-12.png
    - assets/page-1/images/lirtobuddy-1-1.png
    - assets/page-1/images/wifi-SvM.png
    - assets/page-1/images/frame-2109-oe1.png
    - assets/page-1/images/ellipse-22-7dK.png
    - assets/page-1/images/ellipse-3-5A9.png
    - assets/page-1/images/checkmark.png
    - assets/page-1/images/ellipse-20-1pm.png
    - assets/page-1/images/battery-Rs7.png
    - assets/page-1/images/battery-hcD.png
    - assets/page-1/images/wifi-2ZF.png
    - assets/page-1/images/ellipse-19-uPP.png
    - assets/page-1/images/frame-2109-N5F.png
    - assets/page-1/images/back-icon-M8m.png
    - assets/page-1/images/wifi-ioK.png
    - assets/page-1/images/money-mastercard.png
    - assets/page-1/images/bluetooth.png
    - assets/page-1/images/address.png
    - assets/page-1/images/group-19.png
    - assets/page-1/images/wifi-fYm.png
    - assets/page-1/images/mobile-taxi-service.png
    - assets/page-1/images/ellipse-4.png
    - assets/page-1/images/back-icon-tLH.png
    - assets/page-1/images/home-ra5.png
    - assets/page-1/images/wifi-9WZ.png
    - assets/page-1/images/gas12-1.png
    - assets/page-1/images/battery-ZsX.png
    - assets/page-1/images/rewind-button-round.png
    - assets/page-1/images/home-3k5.png
    - assets/page-1/images/gas5k-3-1.png
    - assets/page-1/images/wifi-daH.png
    - assets/page-1/images/mask-group.png
    - assets/page-1/images/back-icon-UjB.png
    - assets/page-1/images/back-icon-6P3.png
    - assets/page-1/images/battery-Dvq.png
    - assets/page-1/images/-aFb.png
    - assets/page-1/images/rectangle-926.png
    - assets/page-1/images/-jKw.png
    - assets/page-1/images/back-icon-U2d.png
    - assets/page-1/images/drop-down.png
    - assets/page-1/images/tracking.png
    - assets/page-1/images/frame-2109-LU1.png
    - assets/page-1/images/gas12-2.png
    - assets/page-1/images/settings.png
    - assets/page-1/images/popular-flag.png
    - assets/page-1/images/switch-off.png
    - assets/page-1/images/popular-check.png
    - assets/page-1/images/frame-2109-KCd.png
    - assets/page-1/images/bank-logo.png
    - assets/page-1/images/frame-2109-2sj.png
    - assets/page-1/images/battery-bfw.png
    - assets/page-1/images/chevrons-chevron-down.png
    - assets/page-1/images/-rjs.png
    - assets/page-1/images/todo-list.png
    - assets/page-1/images/battery-mgM.png
    - assets/page-1/images/back-icon-7kD.png
    - assets/page-1/images/basemap-image-bg.png
    - assets/page-1/images/frame-2109-T3P.png
    - assets/page-1/images/plus.png
    - assets/page-1/images/wifi-hCd.png
    - assets/page-1/images/chip.png
    - assets/page-1/images/frame-2109-JiD.png
    - assets/page-1/images/-E65.png
    - assets/page-1/images/rectangle-927.png
    - assets/page-1/images/-Nxy.png
    - assets/page-1/images/chevrons-chevron-down-aq7.png
    - assets/page-1/images/-Gxq.png
    - assets/page-1/images/back-icon-e4H.png
    - assets/page-1/images/plus-uW1.png
    - assets/page-1/images/purchase-order.png
    - assets/page-1/images/checkbox-active.png
    - assets/page-1/images/money-mastercard-wSh.png
    - assets/page-1/images/-wLD.png
    - assets/page-1/images/fast-forward-round.png
    - assets/page-1/images/address-g2u.png
    - assets/page-1/images/plus-ynh.png
    - assets/page-1/images/settings-Yqo.png
    - assets/page-1/images/google-icon-1.png
    - assets/page-1/images/wifi-66d.png
    - assets/page-1/images/purchase-order-Q7K.png
    - assets/page-1/images/ellipse-19-71j.png
    - assets/page-1/images/ellipse-21-TN9.png
    - assets/page-1/images/minus.png
    - assets/page-1/images/popular-flag-tsT.png
    - assets/page-1/images/mask-group-wUM.png
    - assets/page-1/images/installation-1.png
    - assets/page-1/images/minus-ZbX.png
    - assets/page-1/images/order-completed.png
    - assets/page-1/images/frame-2109-oUD.png
    - assets/page-1/images/switch-on.png
    - assets/page-1/images/battery-X9K.png
    - assets/page-1/images/back-icon-nzM.png
    - assets/page-1/images/plus-56H.png
    - assets/page-1/images/rectangle-928.png
    - assets/page-1/images/rectangle-9.png
    - assets/page-1/images/bank-logo-prD.png
    - assets/page-1/images/rectangle-928-JBB.png
    - assets/page-1/images/images-1.png
    - assets/page-1/images/purchase-order-9UM.png
    - assets/page-1/images/home-VYD.png
    - assets/page-1/images/home-2pH.png
    - assets/page-1/images/rectangle-931.png
    - assets/page-1/images/battery-9hB.png
    - assets/page-1/images/wifi-Nbs.png
    - assets/page-1/images/address-K1s.png
    - assets/page-1/images/rectangle-928-qqT.png
    - assets/page-1/images/settings-8Ro.png
    - assets/page-1/images/chip-7S9.png
    - assets/page-1/images/ok.png
    - assets/page-1/images/rectangle-9-Jh7.png
    - assets/page-1/images/google-icon-2.png
    - assets/page-1/images/laughsthumbnail-1.png
    - assets/page-1/images/wifi-ncH.png
    - assets/page-1/images/image-1-bg.png
    - assets/page-1/images/rectangle-928-vyP.png
    - assets/page-1/images/payment-by-credit-card-processed.png
    - assets/page-1/images/rectangle-925.png
    - assets/page-1/images/rectangle-8.png
    - assets/page-1/images/rectangle-10.png
    - assets/page-1/images/rectangle-928-bry.png
    - assets/page-1/images/rectangle-931-3eR.png
    - assets/page-1/images/rectangle-928-YzV.png
    - assets/page-1/images/rectangle-928-ZKP.png
    - assets/page-1/images/rectangle-19.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
